{{- if .Values.logstash.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-logstash
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.logstash.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.logstash.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range .Values.logstash.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "perfsonar-archive.fullname" $ }}-logstash
                port:
                  number: 11283
          {{- end }}
    {{- end }}
  {{- with .Values.logstash.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
