apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "perfsonar-archive.fullname" . }}-opensearch-node
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: {{ include "perfsonar-archive.fullname" . }}-opensearch-node
  {{- with .Values.opensearchNode.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-node
  template:
    metadata:
      labels:
        app: opensearch-node
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: opensearch-node
          image: {{ .Values.opensearchNode.image.repository }}:{{ .Values.opensearchNode.image.tag }}
          imagePullPolicy: {{ .Values.opensearchNode.image.pullPolicy }}
          env:
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: {{ .Values.opensearchNode.initialAdminPassword | quote }}
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: cluster.name
              value: "opensearch-cluster"
            - name: node.name
              value: "opensearch-node"
            - name: discovery.type
              value: "single-node"
            - name: bootstrap.memory_lock
              value: "true"
            - name: network.host
              value: "0.0.0.0"
            - name: LOGSTASH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "perfsonar-archive.fullname" . }}-logstash-credentials
                  key: password
          ports:
            - containerPort: 9200
            - containerPort: 9600
          {{- with .Values.opensearchNode.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.opensearchNode.persistence.enabled }}
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
            {{- end }}
            - name: opensearch-shared
              mountPath: /etc/perfsonar/opensearch
      volumes:
        - name: opensearch-shared
          persistentVolumeClaim:
            claimName: {{ include "perfsonar-archive.fullname" . }}-opensearch-shared
      {{- with .Values.opensearchNode.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opensearchNode.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.opensearchNode.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: opensearch-data
        labels:
          app.kubernetes.io/instance: {{ .Release.Name }}
      spec:
        accessModes: 
          - {{ .Values.opensearchNode.persistence.accessMode | quote }}
        {{- if .Values.opensearchNode.persistence.storageClass }}
        storageClassName: {{ .Values.opensearchNode.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.opensearchNode.persistence.size | quote }}
{{- end }}
