# Global settings
nameOverride: ""
fullnameOverride: ""

global:
  perfsonarVersion: "5.2.0"

opensearchNode:
  image:
    repository: docker-proxy.grena.ge/perfsonar-archive
    tag: 5.2
    pullPolicy: Always
  opensearchVersion: "2.19.4"
  initialAdminPassword: "perfSONAR123!"
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""
    accessMode: ReadWriteOnce
  resources:
    requests:
      memory: 10Gi
      cpu: 500m
    limits:
      memory: 10Gi
  updateStrategy:
    type: OnDelete
  affinity: {}
  tolerations: []
  service:
    type: ClusterIP

logstash:
  image:
    repository: ghcr.io/perfsonar/logstash
    tag: 5.3.0
    pullPolicy: Always
  logstashVersion: "8.17.3"
  opensearch_output_user: "pscheduler_logstash"
  opensearch_output_password: ""
  strategy:
    type: Recreate
  resources:
    requests:
      memory: 1.5Gi
      cpu: 250m
    limits:
      memory: 1.5Gi
  affinity: {}
  tolerations: []
  service:
    type: ClusterIP

opensearchDashboards:
  image:
    repository: docker-proxy.grena.ge/perfsonar-dashboards
    tag: 5.2
    pullPolicy: Always
  opensearchVersion: "2.19.4"
  # -- Shared volume between the Opensearch container and the Dashboards container
  persistence:
    enabled: true
    size: 250Mi
    storageClassName: ""
    accessMode: ReadWriteOnce
  resources:
    requests:
      memory: 1.5Gi
      cpu: 250m
    limits:
      memory: 1.5Gi
  strategy:
    type: Recreate
  affinity: {}
  tolerations: []
  service:
    type: LoadBalancer
    port: 5601
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: opensearch-dashboards.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

grafana:
  enabled: true

  image:
    repository: ghcr.io/perfsonar/grafana
    tag: "5.3.0"
    pullPolicy: Always

  opensearchVersion: "2.19.4"
  plugins: "grafana-opensearch-datasource,esnet-matrix-panel"
  disableSanitizeHtml: "true"
  provisioningPath: "/usr/lib/perfsonar/grafana/provisioning"

  server:
    rootUrl: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
    serveFromSubPath: "true"

  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  affinity: {}
  tolerations: []
  ingress:
    enabled: true
    className: ""
    annotations:
      nginx.ingress.kubernetes.io/app-root: /grafana
    hosts:
      - host: grafana.local
        paths:
          - path: /grafana
            pathType: Prefix
    tls: []


apache:
  enabled: false

  image:
    repository: httpd
    tag: "2.4"
    pullPolicy: IfNotPresent

  initImage:
    repository: alpine
    tag: "3.20"
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 8443
    targetPort: 8443

  tls:
    enabled: true
    certFile: "/usr/local/apache2/conf/tls/tls.crt"
    keyFile: "/usr/local/apache2/conf/tls/tls.key"
    days: 3650

  grafana:
    path: /grafana
    serviceName: ""
    servicePort: 3000
    scheme: http

  opensearch:
    path: /opensearch
    serviceName: ""
    servicePort: 9200
    scheme: https

  logstash:
    path: /logstash
    serviceName: ""
    servicePort: 11283
    scheme: http

  dashboards:
    serviceName: ""
    servicePort: 5601
    scheme: http  

  extraApacheConfig: ""
