global:
  imagePullSecrets: []

nameOverride: "perfsonar-archive"
fullnameOverride: "perfsonar-archive"


downloader:
  image:
    repository: ghcr.io/perfsonar/perfsonar-archive-docker/perfsonar-downloader
    tag: "5.2.0"
    pullPolicy: IfNotPresent

  persistence:
    archive:
      size: 1Gi
      accessMode: ReadWriteOnce

    logstash:
      size: 1Gi
      accessMode: ReadWriteOnce

    dashboards:
      size: 1Gi
      accessMode: ReadWriteOnce

opensearch:
  enabled: true
  image:
    repository: ghcr.io/perfsonar/perfsonar-archive-docker/opensearch-node
    tag: "5.2.0"
    pullPolicy: IfNotPresent
  initialAdminPassword: "perfSONAR123!"
  existingSecret: ""
  existingSecretKey: OPENSEARCH_INITIAL_ADMIN_PASSWORD
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""
    accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      memory: 10Gi
      cpu: 500m
    limits:
      memory: 10Gi
  affinity: {}
    # podAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app.kubernetes.io/component
    #             operator: In
    #             values:
    #               - perfsonar
    #           - key: app.kubernetes.io/instance
    #             operator: In
    #             values:
    #               - myRelease
    #       topologyKey: kubernetes.io/hostname
  tolerations: []
  service:
    type: ClusterIP
    port: 9200
  sharedConfig:
    size: 1Gi
    accessModes: ["ReadWriteOnce"]

logstash:
  enabled: true
  image:
    repository: ghcr.io/perfsonar/logstash
    tag: 5.3.0
    pullPolicy: IfNotPresent
  strategy:
    type: Recreate
  tolerations: []
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: logstash.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  replicas: 1
  service:
    type: ClusterIP
    port: 11283
  env:
    MONITORING_ENABLED: "false"
    LOG_LEVEL: info
    RATE_CACHE_MAX_ENTRIES: "10000000"
    RATE_CACHE_EXPIRES: "600"
    opensearch_output_user: pscheduler_logstash
    opensearch_output_password: ""
  affinity: {}
    # podAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           - key: app.kubernetes.io/component
    #             operator: In
    #             values:
    #               - perfsonar
    #           - key: app.kubernetes.io/instance
    #             operator: In
    #             values:
    #               - myRelease
    #       topologyKey: kubernetes.io/hostname

  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi

opensearchDashboards:
  enabled: true
  image:
    repository: ghcr.io/perfsonar/perfsonar-archive-docker/opensearch-dashboards
    tag: "5.2.0"
    pullPolicy: IfNotPresent
  opensearchVersion: "2.19.4"
  persistence:
    enabled: true
    size: 250Mi
    storageClassName: ""
    accessMode: ReadWriteOnce
  resources:
    requests:
      memory: 1.5Gi
      cpu: 250m
    limits:
      memory: 1.5Gi
  strategy:
    type: Recreate
  affinity: {}
  tolerations: []
  replicas: 1
  service:
    type: LoadBalancer
    port: 5601
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: opensearch-dashboards.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

grafana:
  enabled: true
  image:
    repository: ghcr.io/perfsonar/grafana
    tag: "5.3.0"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  plugins: grafana-opensearch-datasource,esnet-matrix-panel
  rootUrl: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
  serveFromSubPath: "true"
  opensearchVersion: "2.19.4"
  disableSanitizeHtml: "true"
  provisioningPath: "/usr/lib/perfsonar/grafana/provisioning"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  ingress:
    enabled: true
    className: ""
    annotations:
      nginx.ingress.kubernetes.io/app-root: /grafana
    hosts:
      - host: grafana.local
        paths:
          - path: /grafana
            pathType: Prefix
    tls: []

apache:
  enabled: false
  image:
    repository: httpd
    tag: "2.4"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8443
  tls:
    enabled: true
    existingSecret: ""
  resources: {}